#lang typed/racket/base

(define-namespace-anchor demo)
(define demo-namespace (namespace-anchor->empty-namespace demo))
(parameterize ([current-namespace demo-namespace])
  (namespace-require 'typed/racket/base)
  (namespace-require 'racket/match)
  (namespace-require "../../demo.rkt")
  (namespace-require '(all-except typed/rackunit fail))
  (load "ch1.rktl")
  (load "ch2.rktl")
  (load "ch3.rktl")
  (load "ch4.rktl")
  (load "ch5.rktl")
  #;(load "ch6.rktl")
  #;(load "ch7.rktl")
  #;(load "ch8.rktl")
  (load "ch9.rktl")
  #;(load "ch10.rktl"))
