#lang typed/racket/base

(define-namespace-anchor main)
(define main-namespace (namespace-anchor->empty-namespace main))
(parameterize ([current-namespace main-namespace])
  (namespace-require 'typed/racket/base)
  (namespace-require 'racket/match)
  (namespace-require 'typed/amb)
  (namespace-require "../../main.rkt")
  (namespace-require '(all-except typed/rackunit fail))
  (load "ch1.rktl")
  (load "ch2.rktl")
  (load "ch3.rktl")
  (load "ch4.rktl")
  (load "ch5.rktl")
  (load "ch6.rktl")
  (load "ch7.rktl"))
